name: Deploy Static HTML to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: appservice
        uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: abril2  # Cambia esto al nombre de tu App Service en Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Añade el secreto en GitHub
          package: './basic.html'  # Especifica el directorio que contiene tus archivos HTML estáticos
