name: Deploy Static HTML to Azure

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the job

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2  # Use the Azure Web Apps deploy action
        with:
          app-name: 'abril2'  # Replace this with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Reference the publish profile secret
          package: './basic.html'  # Path to your HTML file to be deployed
